version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
    - '5672:5672'
    - '15672:15672'
    environment:
    RABBITMQ_DEFAULT_USER: guest
    RABBITMQ_DEFAULT_PASS: guest


backend:
  build: ./backend
  environment:
  - RABBIT_URL=amqp://guest:guest@rabbitmq:5672
  ports:
  - '8000:8000'
  depends_on:
  - rabbitmq


frontend:
  build: ./frontend
  ports:
    - '4200:80'
  depends_on:
    - backend
